name: Test build
on:
  push:
  pull_request:

jobs:
  build:
    name: ${{matrix.python}} on ${{matrix.os}}
    runs-on: ${{matrix.os}}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest]
        python:
          - 3.12

    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{matrix.python}}
          cache: 'pip' # caching pip dependencies
          cache-dependency-path: '**/requirements-dev.txt'

      - name: Install esphome
        run: pip install -r test/requirements-dev.txt

      - name: Check config
        run: esphome config test/*.yml

      - name: Build
        run: esphome compile test/*.yml
